### ISSUE TITLE
Support frame generation

### ISSUE THREAD

**Issue by daminetreg** [linkineo/coapi#1]
I would like to add support for frame generation, is it ok for you if I work on this part ?

**Comment by linkineo** [comment]
Salut Damien,

Thanks for your interest. I'm sure we'll have many things to improve in this library :-)
I started frame generation [here](https://github.com/linkineo/coapi/commit/b9425b27c02316d85c98217ac58cafb5bfbdce40) and I should be done by tomorrow.

**Comment by linkineo** [comment]
I completed initial frame generation support [here](https://github.com/linkineo/coapi/commit/662ba3bf027120626b498e65d47cf8169656fd2b) Full tests pending, will be done by tomorrow.

**Comment by daminetreg** [comment]
Cool

**Comment by daminetreg** [comment]
:grinning:
